<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Find Your Game'. $this->translate('Find Your Game'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/animate.css'))
                        ->prependStylesheet($this->basePath('css/block.css'))
                        ->prependStylesheet($this->basePath('css/contextual.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/main.css'))
                        ->prependStylesheet($this->basePath('css/me-theme-preset1.css'))
                        ->prependStylesheet($this->basePath('css/style2.css'))
                        ->prependStylesheet($this->basePath('dist/css/select2.min.css'))
                        ->prependStylesheet('http://54.71.102.208/sites/all/themes/superhero/vendor/bootstrap/css/bootstrap.min.css?o4nt8k')
                        ->prependStylesheet('http://54.71.102.208/sites/all/themes/superhero/vendor/font-awesome/css/font-awesome.min.css?o4nt8k')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('dist/js/select2.min.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body style="padding-top: 0px; padding-bottom: 0px;" class="html not-front logged-in no-sidebars page-node page-node- page-node-90 node-type-page home-page-creative wide ltr">
        <div class="body-innerwrapper">
            <div class="body">
                <section  id="section-header" class="section section-header superhero-sticky">
                    <div class="container">
                        <div class="row">
                            <div class="region region-logo col-xs-6 col-sm-6 col-md-2 col-lg-2">
                                <div class="site-logo clearfix">
                                    <a href="<?php echo $this->url('findmygame/default') ?>" rel="home"><img src="http://54.71.102.208/sites/default/files/findmygame_logo_small.png" id="logo" alt="logo"/></a>
                                </div>
                            </div>
                            <div style="float: right; margin-top: 15px;" class="col-xs-6 col-sm-6 col-md-2 col-lg-2">
                                <div class="clearfix">
                                    <a class="btn btn-primary btn-md" href="/">Back to website</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <?php echo $this->content; ?>
                <?php echo $this->inlineScript() ?>
                <section id="section-footer" class="section section-footer">
                    <div class="container">
                        <div class="row">
                            <div class="region region-footer-second">
                                <div id="block-block-19" class="block block-block contextual-links-region">
                                    <div class="block-contents ">
                                        <div class="contextual-links-wrapper contextual-links-processed"><a class="contextual-links-trigger" href="#">Configure</a>
                                        <ul class="contextual-links"><li class="block-configure first last"><a href="/admin/structure/block/manage/block/19/configure?destination=node/43">Configure block</a></li>
                                        </ul></div>	
                                        <div class="content sh-block-content">
                                          <ul><li><span style="font-size:20px;"><a href="https://www.facebook.com/getmygame" target="_blank"><span data-toggle="tooltip" data-placement="top" class="superhero-tooltip" data-original-title="Facebook"><i class="fa fa-facebook"><span></span></i></span></a></span></li>
                                          <li><span style="font-size:20px;"><a href="https://twitter.com/getmygame" target="_blank"><span data-toggle="tooltip" data-placement="top" class="superhero-tooltip" data-original-title="Twitter"><i class="fa fa-twitter"><span></span></i></span></a></span></li>
                                          <li><span style="font-size:20px;"><a href="https://www.instagram.com/getmygame/" target="_blank"><span data-toggle="tooltip" data-placement="top" class="superhero-tooltip" data-original-title="Instagram"><i class="fa fa-instagram"><span></span></i></span></a></span></li></ul>
                                        </div>
                                    </div>
                                    <div style="clear:both" class="clear-fix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <?php echo $this->googleAnalytics(); ?>
    </body>
</html>
