<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Find Your Game'. $this->translate('Find Your Game'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/animate.css'))
                        ->prependStylesheet($this->basePath('css/block.css'))
                        ->prependStylesheet($this->basePath('css/contextual.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/main.css'))
                        ->prependStylesheet($this->basePath('css/me-theme-preset1.css'))
                        ->prependStylesheet($this->basePath('css/style2.css'))
                        ->prependStylesheet($this->basePath('css/jquery.paginate.css'))
                        ->prependStylesheet($this->basePath('dist/css/select2.min.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('dist/js/select2.min.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/jquery.paginate.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   <a class="navbar-brand" href="<?php echo $this->url('findmygame/default') ?>"><img style="max-height: 25px;" src="<?php echo $this->basePath('blah/img/findmygame_logo_small.png') ?>" alt="Find My Game"/></a>
                </div>
                
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('findmygame/default') ?>"><?php echo $this->translate('Home') ?></a></li>
                         <li><a href="<?php echo $this->url('findmygame/default', array('controller' => 'BarAdmin', 'action' => 'view')) ?>"><?php echo $this->translate('Bars') ?></a></li>
                         <li><a href="<?php echo $this->url('findmygame/default', array('controller' => 'TeamAdmin', 'action' => 'view')) ?>"><?php echo $this->translate('Teams') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
              
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
