<div class="search-wrapper">
   <div class="results-container">
    <section  id="section-feature" class="section section-feature">
        <div class="row"> 
            <div class="region region-feature-first col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <img style="max-width: 500px; margin-left: auto; margin-right: auto;" src="../img/lebron-sad-face-thumb-500xauto-94-1jir7sc.jpg" />   
                <h2 style="text-align: center;">Sorry sports fan, there aren't any blah blah bars within 10 miles of you.</h2>
                <h2 style="text-align: center;">Try searching for another team!</h2>
            </div>
    </section>
   </div>
</div>