<div class="search-wrapper">
    <section  id="section-feature" class="section section-feature">
        <div class="row"> 
            <div class="region region-feature-first col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div style="max-width: 700px; margin-left: auto; margin-right: auto;">
                  <img style="width: 100%;" src="../img/lebron-sad-face-thumb-500xauto-94-1jir7sc.jpg" />   
                  <h2 style="text-align: center;">Sorry sports fan, there aren't any bars that match your search criteria within 10 miles of you. Try searching for another team!</h2>
                </div>
            </div>
    </section>
</div>