<div class="search-wrapper">
   <div class="results-container">
      <h1>You Can Watch Your Game At:</h1>
      <div id="queryresult">
         <?php if (isset($_POST['submit'])) { ?>
        <?php if ($featured != null){
         echo "<h2>Featured Bars</h2>";
        } ?>
         <?php foreach ($featured as $feature) :?>
            <section  id="section-feature" class="section section-feature">
               <div class="">
                  <div class="row">
                     <div class="region region-feature-first col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div id="block-block-51" class="block block-block contextual-links-region">
                           <div class="block-contents" >
                              <div style="box-sizing: border-box;" class="content sh-block-content">
                                 <p><img alt="" src="<?php if(!null == $feature->getBarimage()){ echo "../../module/GameManager/src/GameManager/Assets/" . $feature->getBarimage();} else { echo "http://placehold.it/283x192"; } ?>" style="height:192px; width:283px" /></p>
                              </div>
                           </div>
                           <div style="clear:both" class="clear-fix"></div>
                        </div>
                     </div>
                     <div class="region region-feature-second col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div id="block-block-52" class="block block-block contextual-links-region">
                           <div class="block-contents">
                              <div class="content sh-block-content">
                                 <h1><a href="<?php echo $this->url('findmygame/default', // SUPER IMPORTANT use grace-drops/<segment> NOT ONLY grace-drops
                  array('controller' => 'index', 'action'=>'viewindi', 'id' => $feature->getId()));?>"><?php print $this->escapeHtml($feature->name);?></a></h1>
                                 <p><?php print $feature->bardescription ;?></p>
                                 <!--<p><strong>User Ranking:</strong> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-half-o"></i></p>-->
                                 <a class="btn btn-primary btn-xs" href="https://www.google.com/maps/dir/<?php echo $feature->getLocation();?>/<?php echo $_POST['Location'];?>
      " target="_blank">Directions</a>
                                 <!--<a class="btn btn-primary btn-xs">Rate</a> -->
                                 <a class="btn btn-primary btn-xs" href="<?php echo $this->url('findmygame/default', // SUPER IMPORTANT use grace-drops/<segment> NOT ONLY grace-drops
                  array('controller' => 'index', 'action'=>'viewindi', 'id' => $feature->getId()));?>">More Info...</a>
                              </div>
                           </div>
                           <div style="clear:both" class="clear-fix"></div>
                        </div>
                     </div>
                  </div>
               </div>
            </section>
         <?php endforeach;?>
         
         <hr />
         <?php foreach ($bars as $bar) :?>
            <section  id="section-feature" class="section section-feature">
               <div class="">
                  <div class="row">
                     <div class="region region-feature-first col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div id="block-block-51" class="block block-block contextual-links-region">
                           <div class="block-contents" >
                              <div style="box-sizing: border-box;" class="content sh-block-content">
                                 <p><img alt="" src="<?php if(!null == $bar->getBarimage()){ echo "../../module/GameManager/src/GameManager/Assets/" . $bar->getBarimage();} else { echo "http://placehold.it/283x192"; } ?>" style="height:192px; width:283px" /></p>
                              </div>
                           </div>
                           <div style="clear:both" class="clear-fix"></div>
                        </div>
                     </div>
                     <div class="region region-feature-second col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div id="block-block-52" class="block block-block contextual-links-region">
                           <div class="block-contents">
                              <div class="content sh-block-content">
                                 <h1><a href="<?php echo $this->url('findmygame/default', // SUPER IMPORTANT use grace-drops/<segment> NOT ONLY grace-drops
                  array('controller' => 'index', 'action'=>'viewindi', 'id' => $bar->getId()));?>"><?php print $this->escapeHtml($bar->name);?></a></h1>
                                 <p><?php print $bar->bardescription ;?></p>
                                 <!--<p><strong>User Ranking:</strong> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-half-o"></i></p>-->
                                 <a class="btn btn-primary btn-xs" href="https://www.google.com/maps/dir/<?php echo $bar->getLocation();?>/<?php echo $_POST['Location'];?>
      " target="_blank">Directions</a>
                                 <!--<a class="btn btn-primary btn-xs">Rate</a> -->
                                 <a class="btn btn-primary btn-xs" href="<?php echo $this->url('findmygame/default', // SUPER IMPORTANT use grace-drops/<segment> NOT ONLY grace-drops
                  array('controller' => 'index', 'action'=>'viewindi', 'id' => $bar->getId()));?>">More Info...</a>
                              </div>
                           </div>
                           <div style="clear:both" class="clear-fix"></div>
                        </div>
                     </div>
                  </div>
               </div>
            </section>
         <?php endforeach; ?>
         <?php } ?>
      </div>
      <script type="text/javascript">
            $('#queryresult').paginate({ 'perPage': 10 });
            //$('#queryresult').paginatePosition('above');
         </script>
   </div>
   <div class="map-wrapper">
            <div id="map"></div>
            <div>
               <img src="../img/blue-dot.png"> = Featured Bar
               <img src="../img/red-dot.png"> = Nearby Bar
            </div>
               
               
               <script>
                  
                  var barjson = <?= json_encode($bars); ?>;
                  var featuredjson = <?= json_encode($featured); ?>;
                  var count = Object.keys(barjson).length;
                  var featured_count = Object.keys(featuredjson).length;
                  
                 function initMap() {
                   var DC = {lat: 38.8974286, lng: -77.0660378};
                   var map = new google.maps.Map(document.getElementById('map'), {
                     zoom: 12
                   });
                   setFeatured(map, featuredjson)
                   setMarkers(map, barjson)
                 }
                 
                 function setMarkers(map, barjson){
                     
                     for (var i = 0; i < count; i++){
                        var latLng = new google.maps.LatLng(barjson[i].latitude,barjson[i].longitude)
                        var contentString = '<div id="content">'+
                        '<p><a href="index/viewindi/' + barjson[i].id + '"/>' + barjson[i].name + '</a></p>' +
                        '<p>' + barjson[i].bardescription + '</p>' +
                        '</div>'
                        
                        var marker = new google.maps.Marker({
                        position: latLng,
                        icon: '../img/red-dot.png',
                        map: map
                      });
                        map.setCenter(marker.getPosition())
                        
                        var infowindow = new google.maps.InfoWindow()
                        
                        google.maps.event.addListener(marker,'click', (function(marker,contentString,infowindow){ 
                        return function() {
                           infowindow.setContent(contentString);
                           infowindow.open(map,marker);
                        };
                    })(marker,contentString,infowindow)); 
                   }
                 }
      
               
                  function setFeatured(map, featuredjson) {
                    for (var i = 0; i < featured_count; i++){
                        var latLng = new google.maps.LatLng(featuredjson[i].latitude,featuredjson[i].longitude)
                        var contentString = '<div id="content">'+
                        '<p><a href="index/viewindi/' + featuredjson[i].id + '"/>' + featuredjson[i].name + '</a></p>' +
                        '<p>' + featuredjson[i].bardescription + '</p>' +
                        '</div>'
                        
                        var marker = new google.maps.Marker({
                        position: latLng,
                        icon: '../img/blue-dot.png',
                        map: map
                      });
                        map.setCenter(marker.getPosition())
                        
                        var infowindow = new google.maps.InfoWindow()
                        
                        google.maps.event.addListener(marker,'click', (function(marker,contentString,infowindow){ 
                        return function() {
                           infowindow.setContent(contentString);
                           infowindow.open(map,marker);
                        };
                    })(marker,contentString,infowindow)); 
                   }
                  }
               </script>
               <script async defer
               src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAO9NoMrXAL5uKv0lcMcVpthU8hNsGArDA&callback=initMap">
               </script>
   </div>
   <div class="region region-sidebar-second col-xs-12 col-sm-3 col-md-4 col-lg-4">
	<div id="block-block-47" class="block block-block contact-social block-title-h4 contextual-links-region">
	
	<div class="block-contents ">
	  	            <h3 class="block-title">Find Us On Social Media</h3>
		  <div class="contextual-links-wrapper contextual-links-processed"><a class="contextual-links-trigger" href="#">Configure</a><ul class="contextual-links" style="display: none;"><li class="block-configure first last"><a href="/admin/structure/block/manage/block/47/configure?destination=node/95">Configure block</a></li>
</ul></div>	
	  <div class="content sh-block-content">
	    <ul><li><a href="http://www.facebook.com/getmygame" target="_blank"><i class="fa fa-facebook"><span></span></i></a></li>
<li><a href="http://www.twitter.com/getmygame" target="_blank"><i class="fa fa-twitter"><span></span></i></a></li>
<li><a href="http://www.instagram.com/getmygame" target="_blank"><i class="fa fa-instagram"><span></span></i></a></li>

</ul>	  </div>
	</div>
	<div style="clear:both" class="clear-fix"></div>
</div>
</div>
</div>