<?php
echo '<h1>Delete a Bar</h1>';

?>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($bar->getId()); ?>' by ID
    '<?php echo $this->escapeHtml($bar->getName()); ?>'?
</p>
<?php
$url = $this->url('findmygame/default', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $bar->getId(); ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>