<script type="text/javascript">
$(document).ready(function() {
  $(".affiliations").select2();
  $(".sports").select2();
  $(".leagues").select2();
});
</script>
<?php
echo 'Edit Bar';

$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('findmygame/default', array('controller' => 'Index', 'action' => 'edit', 'id' => $this->id))); //'contact/process'));


// Set the method attribute for the form
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();