<script type="text/javascript">
$(document).ready(function() {
  $(".affiliations").select2();
  $(".sports").select2();
  $(".leagues").select2();
});
</script>
<script src="../../../ckeditor/ckeditor.js"></script>
<?php

$form = $this->form;

$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>

<script>
  CKEDITOR.replace( 'ckeditor' );
</script>