<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class GameManagerModelsBarHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['location'])) {
            $value = $data['location'];
            $return = (string) $value;
            $this->class->reflFields['location']->setValue($document, $return);
            $hydratedData['location'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['hours'])) {
            $value = $data['hours'];
            $return = (string) $value;
            $this->class->reflFields['hours']->setValue($document, $return);
            $hydratedData['hours'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['phone'])) {
            $value = $data['phone'];
            $return = (string) $value;
            $this->class->reflFields['phone']->setValue($document, $return);
            $hydratedData['phone'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['website'])) {
            $value = $data['website'];
            $return = (string) $value;
            $this->class->reflFields['website']->setValue($document, $return);
            $hydratedData['website'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['bardescription'])) {
            $value = $data['bardescription'];
            $return = (string) $value;
            $this->class->reflFields['bardescription']->setValue($document, $return);
            $hydratedData['bardescription'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['barimage'])) {
            $value = $data['barimage'];
            $return = (string) $value;
            $this->class->reflFields['barimage']->setValue($document, $return);
            $hydratedData['barimage'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['facebook'])) {
            $value = $data['facebook'];
            $return = (string) $value;
            $this->class->reflFields['facebook']->setValue($document, $return);
            $hydratedData['facebook'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['twitter'])) {
            $value = $data['twitter'];
            $return = (string) $value;
            $this->class->reflFields['twitter']->setValue($document, $return);
            $hydratedData['twitter'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['snapchat'])) {
            $value = $data['snapchat'];
            $return = (string) $value;
            $this->class->reflFields['snapchat']->setValue($document, $return);
            $hydratedData['snapchat'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['instagram'])) {
            $value = $data['instagram'];
            $return = (string) $value;
            $this->class->reflFields['instagram']->setValue($document, $return);
            $hydratedData['instagram'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['affiliations'])) {
            $value = $data['affiliations'];
            $return = $value;
            $this->class->reflFields['affiliations']->setValue($document, $return);
            $hydratedData['affiliations'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['leagues'])) {
            $value = $data['leagues'];
            $return = $value;
            $this->class->reflFields['leagues']->setValue($document, $return);
            $hydratedData['leagues'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['sports'])) {
            $value = $data['sports'];
            $return = $value;
            $this->class->reflFields['sports']->setValue($document, $return);
            $hydratedData['sports'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['vibe'])) {
            $value = $data['vibe'];
            $return = (int) $value;
            $this->class->reflFields['vibe']->setValue($document, $return);
            $hydratedData['vibe'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['ageappropriate'])) {
            $value = $data['ageappropriate'];
            $return = (int) $value;
            $this->class->reflFields['ageappropriate']->setValue($document, $return);
            $hydratedData['ageappropriate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['televisions'])) {
            $value = $data['televisions'];
            $return = (string) $value;
            $this->class->reflFields['televisions']->setValue($document, $return);
            $hydratedData['televisions'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['outdoorseating'])) {
            $value = $data['outdoorseating'];
            $return = (int) $value;
            $this->class->reflFields['outdoorseating']->setValue($document, $return);
            $hydratedData['outdoorseating'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['capacity'])) {
            $value = $data['capacity'];
            $return = (int) $value;
            $this->class->reflFields['capacity']->setValue($document, $return);
            $hydratedData['capacity'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['type'])) {
            $value = $data['type'];
            $return = (int) $value;
            $this->class->reflFields['type']->setValue($document, $return);
            $hydratedData['type'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['staples'])) {
            $value = $data['staples'];
            $return = (string) $value;
            $this->class->reflFields['staples']->setValue($document, $return);
            $hydratedData['staples'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['menu'])) {
            $value = $data['menu'];
            $return = (string) $value;
            $this->class->reflFields['menu']->setValue($document, $return);
            $hydratedData['menu'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['foodprices'])) {
            $value = $data['foodprices'];
            $return = (int) $value;
            $this->class->reflFields['foodprices']->setValue($document, $return);
            $hydratedData['foodprices'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['happyhour'])) {
            $value = $data['happyhour'];
            $return = (int) $value;
            $this->class->reflFields['happyhour']->setValue($document, $return);
            $hydratedData['happyhour'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['hhtime'])) {
            $value = $data['hhtime'];
            $return = (string) $value;
            $this->class->reflFields['hhtime']->setValue($document, $return);
            $hydratedData['hhtime'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['fullbar'])) {
            $value = $data['fullbar'];
            $return = (int) $value;
            $this->class->reflFields['fullbar']->setValue($document, $return);
            $hydratedData['fullbar'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['drinkspecials'])) {
            $value = $data['drinkspecials'];
            $return = (string) $value;
            $this->class->reflFields['drinkspecials']->setValue($document, $return);
            $hydratedData['drinkspecials'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['barnumber'])) {
            $value = $data['barnumber'];
            $return = (int) $value;
            $this->class->reflFields['barnumber']->setValue($document, $return);
            $hydratedData['barnumber'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['publictrans'])) {
            $value = $data['publictrans'];
            $return = (int) $value;
            $this->class->reflFields['publictrans']->setValue($document, $return);
            $hydratedData['publictrans'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['trainstation'])) {
            $value = $data['trainstation'];
            $return = (string) $value;
            $this->class->reflFields['trainstation']->setValue($document, $return);
            $hydratedData['trainstation'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['parking'])) {
            $value = $data['parking'];
            $return = (int) $value;
            $this->class->reflFields['parking']->setValue($document, $return);
            $hydratedData['parking'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['parkingtype'])) {
            $value = $data['parkingtype'];
            $return = (int) $value;
            $this->class->reflFields['parkingtype']->setValue($document, $return);
            $hydratedData['parkingtype'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['tvspecials'])) {
            $value = $data['tvspecials'];
            $return = (string) $value;
            $this->class->reflFields['tvspecials']->setValue($document, $return);
            $hydratedData['tvspecials'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['tvchange'])) {
            $value = $data['tvchange'];
            $return = (int) $value;
            $this->class->reflFields['tvchange']->setValue($document, $return);
            $hydratedData['tvchange'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['music'])) {
            $value = $data['music'];
            $return = (string) $value;
            $this->class->reflFields['music']->setValue($document, $return);
            $hydratedData['music'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['dj'])) {
            $value = $data['dj'];
            $return = (string) $value;
            $this->class->reflFields['dj']->setValue($document, $return);
            $hydratedData['dj'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['otherbar'])) {
            $value = $data['otherbar'];
            $return = (string) $value;
            $this->class->reflFields['otherbar']->setValue($document, $return);
            $hydratedData['otherbar'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['dresscode'])) {
            $value = $data['dresscode'];
            $return = (int) $value;
            $this->class->reflFields['dresscode']->setValue($document, $return);
            $hydratedData['dresscode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['notes'])) {
            $value = $data['notes'];
            $return = (string) $value;
            $this->class->reflFields['notes']->setValue($document, $return);
            $hydratedData['notes'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['latitude'])) {
            $value = $data['latitude'];
            $return = (float) $value;
            $this->class->reflFields['latitude']->setValue($document, $return);
            $hydratedData['latitude'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['longitude'])) {
            $value = $data['longitude'];
            $return = (float) $value;
            $this->class->reflFields['longitude']->setValue($document, $return);
            $hydratedData['longitude'] = $return;
        }

        /** @EmbedOne */
        if (isset($data['point'])) {
            $embeddedDocument = $data['point'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['point'], $embeddedDocument);
            $embeddedMetadata = $this->dm->getClassMetadata($className);
            $return = $embeddedMetadata->newInstance();

            $this->unitOfWork->setParentAssociation($return, $this->class->fieldMappings['point'], $document, 'point');

            $embeddedData = $this->dm->getHydratorFactory()->hydrate($return, $embeddedDocument, $hints);
            $embeddedId = $embeddedMetadata->identifier && isset($embeddedData[$embeddedMetadata->identifier]) ? $embeddedData[$embeddedMetadata->identifier] : null;

            $this->unitOfWork->registerManaged($return, $embeddedId, $embeddedData);

            $this->class->reflFields['point']->setValue($document, $return);
            $hydratedData['point'] = $return;
        }
        return $hydratedData;
    }
}