<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class GameManagerModelsTeamHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['teamname']) || (! empty($this->class->fieldMappings['teamname']['nullable']) && array_key_exists('teamname', $data))) {
            $value = $data['teamname'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['teamname']->setValue($document, $return);
            $hydratedData['teamname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['sport']) || (! empty($this->class->fieldMappings['sport']['nullable']) && array_key_exists('sport', $data))) {
            $value = $data['sport'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['sport']->setValue($document, $return);
            $hydratedData['sport'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['league']) || (! empty($this->class->fieldMappings['league']['nullable']) && array_key_exists('league', $data))) {
            $value = $data['league'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['league']->setValue($document, $return);
            $hydratedData['league'] = $return;
        }
        return $hydratedData;
    }
}