<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ZendXml\\' => array($vendorDir . '/zendframework/zendxml/library'),
    'ZendDiagnostics\\' => array($vendorDir . '/zendframework/zenddiagnostics/src'),
    'ZendDiagnosticsTest\\' => array($vendorDir . '/zendframework/zenddiagnostics/tests'),
    'ZFTool\\' => array($vendorDir . '/zendframework/zftool/src'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Doctrine\\ODM\\MongoDB' => array($vendorDir . '/doctrine/mongodb-odm/lib'),
    'Doctrine\\MongoDB' => array($vendorDir . '/doctrine/mongodb/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'DoctrineMongoODMModule\\' => array($vendorDir . '/doctrine/doctrine-mongo-odm-module/src'),
    'DoctrineMongoODMModuleTest\\' => array($vendorDir . '/doctrine/doctrine-mongo-odm-module/tests'),
    'DoctrineModule\\' => array($vendorDir . '/doctrine/doctrine-module/src'),
);
